/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // tutorialSidebar: [
  //   {
  //     type: "category",
  //     label: "Getting Started",
  //     items: [
  //       "getting-started/authentication",
  //       "getting-started/apiQuickStart",
  //       "getting-started/designToolQuickStart",
  //     ],
  //   },
  //   {
  //     type: "category",
  //     label: "Guides",
  //     items: ["guides/integrating-design-tool", "guides/integrating-rest-api"],
  //   },
  //   // {
  //   //   type: 'link',
  //   //   label: ''
  //   //   href:
  //   // }
  // ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};
