/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  user: {
    "Shop Owner": [
      "users-manual/get-started",
      // "users-manual/introduce",
      "users-manual/dashboard",
      "users-manual/online-design",
      "users-manual/integrations",
    ],
  },
  developer: {
    "Developer's Guide": [
      "api-sdk/intro",
      "api-sdk/design-tool",
      "api-sdk/api-overview",
      "api-sdk/webhooks",
    ],
  },
  api: [
    "reference/design-tool-sdk",
    "reference/uploader-sdk",
    "reference/rest-api",
  ],
  //   "Online Design tool": {
  //     "Intro online design tool": [
  //       "online-design/introduce",
  //       "online-design/use-text",
  //       "online-design/use-clipart",
  //       "online-design/use-image",
  //       "online-design/use-element",
  //       "online-design/use-layers",
  //     ],
  //   },
};
